
package views;

import configuration.ParamConfig;
import configuration.SpringConfig;
import entities.Pessoa;
import services.PessoaService;
import services.RegistroEventoTempService;

public class TelaLogin extends javax.swing.JFrame {

    public TelaLogin() {
        initComponents();
        SpringConfig.context.getBean(RegistroEventoTempService.class).find();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCadastrar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        fieldInsertIdUsuario = new javax.swing.JTextField();
        buttonInsertSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        fieldInsertIdEvento = new javax.swing.JTextField();
        fieldInsertNomeUsuario = new javax.swing.JTextField();
        fieldInsertNomeEvento = new javax.swing.JTextField();
        dialogCertificados = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        fieldInsertIdUsuario1 = new javax.swing.JTextField();
        buttonInsertSalvar1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        fieldInsertIdEvento1 = new javax.swing.JTextField();
        fieldInsertNomeUsuario1 = new javax.swing.JTextField();
        fieldInsertNomeEvento1 = new javax.swing.JTextField();
        panelLogin = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        fieldLogin = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        fieldSenha = new javax.swing.JPasswordField();
        labelLoginErro = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        buttonCertificados = new javax.swing.JButton();

        dialogCadastrar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogCadastrar.setTitle("Cadastrar Usuário");
        dialogCadastrar.setModal(true);
        dialogCadastrar.setResizable(false);
        dialogCadastrar.setSize(new java.awt.Dimension(360, 200));

        jLabel6.setText("Usuário:");

        fieldInsertIdUsuario.setEditable(false);
        fieldInsertIdUsuario.setFocusable(false);

        buttonInsertSalvar.setText("Salvar");
        buttonInsertSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertSalvarActionPerformed(evt);
            }
        });

        jLabel9.setText("Evento:");

        fieldInsertNomeUsuario.setEditable(false);
        fieldInsertNomeUsuario.setFocusable(false);

        javax.swing.GroupLayout dialogCadastrarLayout = new javax.swing.GroupLayout(dialogCadastrar.getContentPane());
        dialogCadastrar.getContentPane().setLayout(dialogCadastrarLayout);
        dialogCadastrarLayout.setHorizontalGroup(
            dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCadastrarLayout.createSequentialGroup()
                        .addComponent(buttonInsertSalvar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogCadastrarLayout.createSequentialGroup()
                        .addGroup(dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldInsertIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(fieldInsertIdEvento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldInsertNomeUsuario)
                            .addComponent(fieldInsertNomeEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        dialogCadastrarLayout.setVerticalGroup(
            dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldInsertIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInsertNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldInsertIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInsertNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(buttonInsertSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogCertificados.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogCertificados.setTitle("Certificados");
        dialogCertificados.setModal(true);
        dialogCertificados.setResizable(false);
        dialogCertificados.setSize(new java.awt.Dimension(360, 200));

        jLabel7.setText("Usuário:");

        fieldInsertIdUsuario1.setEditable(false);
        fieldInsertIdUsuario1.setFocusable(false);

        buttonInsertSalvar1.setText("Salvar");
        buttonInsertSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertSalvar1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Evento:");

        fieldInsertNomeUsuario1.setEditable(false);
        fieldInsertNomeUsuario1.setFocusable(false);

        javax.swing.GroupLayout dialogCertificadosLayout = new javax.swing.GroupLayout(dialogCertificados.getContentPane());
        dialogCertificados.getContentPane().setLayout(dialogCertificadosLayout);
        dialogCertificadosLayout.setHorizontalGroup(
            dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCertificadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCertificadosLayout.createSequentialGroup()
                        .addComponent(buttonInsertSalvar1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogCertificadosLayout.createSequentialGroup()
                        .addGroup(dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldInsertIdUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(fieldInsertIdEvento1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldInsertNomeUsuario1)
                            .addComponent(fieldInsertNomeEvento1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        dialogCertificadosLayout.setVerticalGroup(
            dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCertificadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldInsertIdUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInsertNomeUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldInsertIdEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInsertNomeEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(buttonInsertSalvar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eventus");

        panelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Entre"));

        labelLogin.setText("Login:");

        labelSenha.setText("Senha:");

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        labelLoginErro.setForeground(java.awt.Color.red);

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonCertificados.setText("Certificados");
        buttonCertificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCertificadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogin)
                    .addComponent(labelSenha))
                .addGap(10, 10, 10)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(fieldLogin)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLoginErro)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(buttonLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonCertificados)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin)
                    .addComponent(fieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLoginErro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonCadastrar)
                    .addComponent(buttonCertificados))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        buttonLogin.setEnabled(false);
        
        if ( fieldLogin.getText().equals("") || fieldSenha.getPassword().length < 1 ) {
            labelLoginErro.setText("Informe login e senha");
            labelLoginErro.setVisible(true);
        } else {
            //PessoaService usuarioService = SpringConfig.context.getBean(PessoaService.class);
            PessoaService usuarioService = new PessoaService();
            
            /*            
            String senha = new String(fieldSenha.getPassword());

            try {
                // Create MessageDigest instance for MD5
                MessageDigest md = MessageDigest.getInstance("MD5");
                //Add password bytes to digest
                md.update(senha.getBytes());
                //Get the hash's bytes
                byte[] bytes = md.digest();
                //This bytes[] has bytes in decimal format;
                //Convert it to hexadecimal format
                StringBuilder sb = new StringBuilder();
                for(int i=0; i< bytes.length ;i++) {
                    sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
                }
                //Get complete hashed password in hex format
                senha = sb.toString();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            } */
            
//            funcionarioLogado = usuarioService.findById(3);
            
//            funcionarioLogado.setSenha(senha);
            
//            usuarioService.update(funcionarioLogado);
            
            Pessoa usuarioLogado = usuarioService.loginUsuario(fieldLogin.getText(), new String(fieldSenha.getPassword()));

            if ( usuarioLogado != null ){
                labelLoginErro.setText("");
                labelLoginErro.setVisible(false);
                
                ParamConfig config = new ParamConfig(usuarioLogado);

                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        TelaLogin.this.setVisible(false);
                        new TelaInicial().setVisible(true);
                    }
                });
            } else {
                labelLoginErro.setText("Usuário ou senha incorretos.");
                labelLoginErro.setVisible(true);
            }
        }
        
        buttonLogin.setEnabled(true);
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        dialogCadastrar.setLocationRelativeTo(null);
        dialogCadastrar.setVisible(true);
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonCertificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCertificadosActionPerformed
        dialogCertificados.setLocationRelativeTo(null);
        dialogCertificados.setVisible(true);
    }//GEN-LAST:event_buttonCertificadosActionPerformed

    private void buttonInsertSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertSalvarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*registroEventoService.insert(entity);

                fieldInsertIdUsuario.setText("");
                fieldInsertNomeUsuario.setText("");
                fieldInsertIdEvento.setText("");
                fieldInsertNomeEvento.setText("");

                dialogCadastrar.dispose();
                load();*/
            }
        });
    }//GEN-LAST:event_buttonInsertSalvarActionPerformed

    private void buttonInsertSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertSalvar1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*registroEventoService.insert(entity);

                fieldInsertIdUsuario.setText("");
                fieldInsertNomeUsuario.setText("");
                fieldInsertIdEvento.setText("");
                fieldInsertNomeEvento.setText("");

                dialogCertificados.dispose();
                load();*/
            }
        });
    }//GEN-LAST:event_buttonInsertSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonCertificados;
    private javax.swing.JButton buttonInsertSalvar;
    private javax.swing.JButton buttonInsertSalvar1;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JDialog dialogCadastrar;
    private javax.swing.JDialog dialogCertificados;
    private javax.swing.JTextField fieldInsertIdEvento;
    private javax.swing.JTextField fieldInsertIdEvento1;
    private javax.swing.JTextField fieldInsertIdUsuario;
    private javax.swing.JTextField fieldInsertIdUsuario1;
    private javax.swing.JTextField fieldInsertNomeEvento;
    private javax.swing.JTextField fieldInsertNomeEvento1;
    private javax.swing.JTextField fieldInsertNomeUsuario;
    private javax.swing.JTextField fieldInsertNomeUsuario1;
    private javax.swing.JTextField fieldLogin;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLoginErro;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPanel panelLogin;
    // End of variables declaration//GEN-END:variables
}
